config/routes.rb
Rails.application.routes.draw do
  resources :list_items do
    collection do
      post :sort
    end
  end
  resources :lists
end

app/models/listopia_list_base.rb
module ListopiaListBase
  extend ActiveSupport::Concern

  included do
    attr_accessible :bag, :description, :items_count, :name, :slug, :type, :user_id, :user
    has_many :list_items, :dependent => :destroy, :order => 'position'
    belongs_to :user
    validates_presence_of :name
  end
  def remove(thing)
    ListItem.transaction do
      self.list_items.where(["resource_id = ? and resource_type = ?", thing.id, thing.class.name]).each(&:destroy)
    end
  end
  
  def contains?(thing)
    ListItem.where(["list_id = ?", self.id]).
      where(:resource_id => thing.id, :resource_type => thing.class.name).any?
  end

  def add(thing)
    self.list_items << ListItem.new(:resource => thing) unless contains?(thing)
    true
  end
  private
end

app/models/listopia_list_item_base.rb
module ListopiaListItemBase
  extend ActiveSupport::Concern

  included do
    attr_accessible :list_id, :position, :resource_id, :resource_type, :list, :resource, :bag
    belongs_to :list, :counter_cache => :items_count
    belongs_to :resource, :polymorphic => true, :counter_cache => :list_count
    
    scope :resource, lambda{ |r| where(:resource_id => r.id, :resource_type => r.class.name) }      
  end
  
  def name
    resource.name
  end
  private
end

app/controllers/listopia_list_items_controller.rb
module ListopiaListItemsController
  # Base functionality of ListItems Controller
  #
  # class ListItemsController < ApplicationController
  #   include ListopiaListItemsController::Base
  # end
  module Base
    extend ActiveSupport::Concern
    # GET /list_items
    # GET /list_items.json
    def index
     @list_items = ListItem.all

     respond_to do |format|
       format.html { render "listopia/list_items/index"}
       format.json { render json: @list_items }
     end
    end

    # GET /list_items/1
    # GET /list_items/1.json
    def show
     @list_item = ListItem.find(params[:id])

     respond_to do |format|
       format.html { render "listopia/list_items/show"}
       format.json { render json: @list_item }
     end
    end

    # GET /list_items/new
    # GET /list_items/new.json
    def new
     @list_item = ListItem.new

     respond_to do |format|
       format.html { render "listopia/list_items/new"}
       format.json { render json: @list_item }
     end
    end

    # GET /list_items/1/edit
    def edit
     @list_item = ListItem.find(params[:id])
     respond_to do |format|
       format.html { render "listopia/list_items/edit"}
       format.json { render json: @list_item }
     end
    end

    # POST /list_items
    # POST /list_items.json
    def create
     @list_item = ListItem.new(params[:list_item])
     
     respond_to do |format|
       if @list_item.list.add(@list_item.resource)
         format.html { redirect_to @list_item.list, notice: 'List item was successfully created.' }
         format.json { render json: @list_item.list, status: :created, location: @list_item }
       else
         format.html { render action: "new" }
         format.json { render json: @list_item.errors, status: :unprocessable_entity }
       end
     end
    end

    # PUT /list_items/1
    # PUT /list_items/1.json
    def update
     @list_item = ListItem.find(params[:id])

     respond_to do |format|
       if @list_item.update_attributes(params[:list_item])
         format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
         format.json { head :no_content }
       else
         format.html { render action: "edit" }
         format.json { render json: @list_item.errors, status: :unprocessable_entity }
       end
     end
    end

    # DELETE /list_items/1
    # DELETE /list_items/1.json
    def destroy
     @list_item = ListItem.find(params[:id])
     @list_item.destroy

     respond_to do |format|
       format.html { redirect_to list_items_url }
       format.json { head :no_content }
     end
    end
    
    def sort
      params[:list_item].each_with_index do |id, index|
        ListItem.update_all(['position=?', index+1], ['id=?', id])
      end
      respond_to do |format|
        format.html {redirect_to "/lists/#{params[:list_id]}"}
        format.json {head :no_content}
      end      
    end

  end#Base
end

app/controllers/listopia_lists_controller.rb
module ListopiaListsController
  # Base functionality of Lists Controller
  #
  # class ListsController < ApplicationController
  #   include ListopiaListsController::Base
  # end
  module Base
    extend ActiveSupport::Concern
    # GET /lists
    # GET /lists.json
    def index
      @lists = List.all
  
      respond_to do |format|
        format.html { render "listopia/lists/index"}
        format.json { render json: @lists }
      end
    end
  
    # GET /lists/1
    # GET /lists/1.json
    def show
      @list = List.find(params[:id])
  
      respond_to do |format|
        format.html { render "listopia/lists/show"}
        format.json { render json: @list }
      end
    end
  
    # GET /lists/new
    # GET /lists/new.json
    def new
      @list = List.new
  
      respond_to do |format|
        format.html { render "listopia/lists/new"}
        format.json { render json: @list }
      end
    end
  
    # GET /lists/1/edit
    def edit
      @list = List.find(params[:id])
      respond_to do |format|
        format.html { render "listopia/lists/edit"}
        format.json { render json: @list }
      end      
    end
  
    # POST /lists
    # POST /lists.json
    def create
      @list = List.new(params[:list])
  
      respond_to do |format|
        if @list.save
          format.html { redirect_to @list, notice: 'List was successfully created.' }
          format.json { render json: @list, status: :created, location: @list }
        else
          format.html { render action: "new" }
          format.json { render json: @list.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /lists/1
    # PUT /lists/1.json
    def update
      @list = List.find(params[:id])
  
      respond_to do |format|
        if @list.update_attributes(params[:list])
          format.html { redirect_to @list, notice: 'List was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @list.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /lists/1
    # DELETE /lists/1.json
    def destroy
      @list = List.find(params[:id])
      @list.destroy
  
      respond_to do |format|
        format.html { redirect_to lists_url }
        format.json { head :no_content }
      end
    end
  end#Base
end

app/helpers/listopia_helper.rb
module ListopiaHelper
end

app/views/layouts/listopia/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listopia</title>
  <%= stylesheet_link_tag    "listopia/application", :media => "all" %>
  <%= javascript_include_tag "listopia/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/listopia/application.html.haml
!!!
%html
  %head
    %title Listopia
    = stylesheet_link_tag    "listopia/application", :media => "all"
    = javascript_include_tag "listopia/application"
    = csrf_meta_tags
  %body
    = yield

app/views/listopia/lists/_form.html.haml
= form_for(@list) do |f|
  - if @list.errors.any?
    #error_explanation
      %h2
        = pluralize(@list.errors.count, "error")
        prohibited this list from being saved:
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/listopia/lists/edit.html.haml
%h1 Editing list
= render 'listopia/lists/form'
= link_to 'Show', @list
|
\#{link_to 'Back', lists_path}

app/views/listopia/lists/index.html.haml
%h1 Listing lists
%table
  %tr
    %th Name
    %th Type
    %th Description
    %th Slug
    %th Bag
    %th User
    %th Items count
    %th
    %th
    %th
  - @lists.each do |list|
    %tr
      %td= list.name
      %td= list.description
      %td= list.slug
      %td= list.bag
      %td= list.user_id
      %td= list.items_count
      %td= link_to 'Show', list
      %td= link_to 'Edit', edit_list_path(list)
      %td= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New List', new_list_path

app/views/listopia/lists/new.html.haml
%h1 New list
= render 'listopia/lists/form'
= link_to 'Back', lists_path

app/views/listopia/lists/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @list.name
%p
  %b Description:
  = @list.description
- if @list.list_items.empty?
  .alert.alert-notice
    %h2 Your list is empty
- else
  %ul.ui-sortable
    %li{:id => "list_#{@list.id}", :style => "display:none;"}
    - @list.list_items.each do |item|
      %li{:id => "list_item_#{item.id}"}
        = item.name
        = link_to "remove", list_item_path(item.id, :format => :json), 
          "data-method" => :delete, :remote => true, :confirm => "Are you sure?", :class => "listopia-rm"
/ %h2 Add to your list
/ = form_for ListItem.new do |f|
/   = f.select :resource_id, YOURMODEL.all.map { |u| [u.name, u.id] }, { include_blank: true }, { class: 'chzn-select', style: "width: 300px;" }
/   = f.hidden_field :resource_type, :value => "YourModelType"
/   = f.hidden_field :list_id, :value => @list.id
/   %br
/   = f.submit "Save"